[package]
name = "cast-server"
version = "0.13.1"
edition = "2021"
authors = [
    "Maciej Rak <raku@walletconnect.com>"
]
build = "build.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6", features = ["json"] }
tower = "0.4"
tower-http = { version = "0.3", features = ["trace", "cors"] }
hyper = "0.14"

# Database
mongodb = "2.3.1"
# Seralisation

serde = { version = "1.0", features = ["derive"] }

# Env Vars
dotenv = "0.15"
envy = "0.4"

# Metrics & Traces
prometheus-core = { package = "prometheus", version = "0.13" }
opentelemetry = { version = "0.18", features = ["metrics", "rt-tokio"] }
opentelemetry-prometheus = "0.11"
opentelemetry-otlp = "0.11"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "parking_lot"] }
tracing-appender = "0.2"
tracing-opentelemetry = "0.18"
atty = "0.2"
log = "0.4"

# Misc
build-info = "0.0"
thiserror = "1.0"
async-trait = "0.1"
tokio-stream = "0.1.11"
regex = "1.7.1"
tungstenite = {version = "0.18.0", features =["native-tls"] }
url = "2.3.1"
sha256 = "1.1.1"
chacha20poly1305 = "0.10.1"
serde_json = "1.0.91"
hex = "0.4.3"
ed25519-dalek = "1.0.1"
rand = "0.7.0"
rand_core = "0.5.0"
base64 = "0.21.0"
ring = "0.16.20"
jsonwebtoken = "8.2.0"
data-encoding = "2.3.3"
chrono = "0.4.23"
derive_more = "0.99.17"
bs58 = "0.4.0"
futures = "0.3.26"
async-tungstenite = {version = "0.20.0", features = ["tokio", "tokio-native-tls"]}
dashmap = "5.4.0"

walletconnect_sdk = { git = "https://github.com/WalletConnect/WalletConnectRust.git", features= ["rpc"]}

[dev-dependencies]
test-context = "0.1"
reqwest = "0.11"

[build-dependencies]
build-info-build = "0.0"
