version: '3.9'
services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "3001:16686"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root

  rust-http-starter:
    build: .
    depends_on:
      - jaeger
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgres://postgres:root@postgres:5432/postgres
      - TELEMETRY_ENABLED=true
      - TELEMETRY_GRPC_URL=http://jaeger:4317