name: cd
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "terraform/**"
  release:
    types: ["published"]

concurrency:
  # Only allow for one action to run at once, queue any others
  group: cd
  # Don't cancel existing
  cancel-in-progress: false

jobs:

  ##############################################################################
  # Versioning

  get-version:
    if: ${{ github.ref == 'enable when a version is available' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.clean_version.outputs.version }}
    steps:
      - name: Get latest release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        if: github.event_name != 'release'
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Get release value
        id: get
        uses: actions/github-script@v6
        env:
          LATEST_TAG: ${{ steps.latest_release.outputs.release }}
        with:
          result-encoding: string
          script: |
            if (context.eventName == "release") {
              return context.payload.release.tag_name
            } else {
              return process.env.LATEST_TAG
            }

      - name: Clean version
        id: clean_version
        run: |
          version=$(echo "${{ steps.get.outputs.result }}" | sed 's/v//g')
          echo "version=$version" >> $GITHUB_OUTPUT


  ##############################################################################
  # Staging

  deploy-infra-staging:
#    needs:
#      - get-version
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      environment: 'staging'
      environment_url: https://staging.cast.walletconnect.com/health

  validate-staging:
    needs:
      - deploy-infra-staging
    uses: ./.github/workflows/validate.yml
    with:
      environment: 'staging'


  ##############################################################################
  # Prod

  deploy-infra-prod:
    needs:
#      - get-version
      - validate-staging
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      environment: 'prod'
      environment_url: https://staging.cast.walletconnect.com/health

  validate-prod:
    needs: [deploy-infra-prod]
    uses: ./.github/workflows/validate.yml
    with:
      environment: 'prod'
