name: cd
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  # Only allow for one action to run at once, queue any others
  group: cd
  # Don't cancel existing
  cancel-in-progress: false

jobs:
  ##############################################################################
  # Versioning

  get-version:
    permissions:
      contents: read
    # if: ${{ github.ref == 'enable when a version is available' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.clean_version.outputs.version }}
    steps:
      - name: Get latest release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        if: github.event_name != 'release'
        with:
          repository: ${{ github.repository }}
          excludes: draft

      - name: Get release value
        id: get
        uses: actions/github-script@v6
        env:
          LATEST_TAG: ${{ steps.latest_release.outputs.release }}
        with:
          result-encoding: string
          script: |
            if (context.eventName == "release") {
              return context.payload.release.tag_name
            } else {
              return process.env.LATEST_TAG
            }

      - name: Clean version
        id: clean_version
        run: |
          version=$(echo "${{ steps.get.outputs.result }}" | sed 's/v//g')
          echo "version=$version" >> $GITHUB_OUTPUT

  ##############################################################################
  # Staging

  deploy-infra-staging:
    needs:
      - get-version
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: "staging"
      environment_url: https://staging.cast.walletconnect.com/health
      relay_url: "wss://staging.relay.walletconnect.com"
      cast_url: "https://staging.cast.walletconnect.com"

  validate-staging-rust:
    needs: deploy-infra-staging
    secrets: inherit
    uses: ./.github/workflows/validate.yml
    with:
      environment: "STAGING"

  validate-staging-swift:       
    needs: deploy-infra-staging
    uses: ./.github/workflows/validate_swift.yml
    with:
      notify-endpoint: 'staging.cast.walletconnect.com'
      relay-endpoint: 'staging.relay.walletconnect.com' 


  ##############################################################################
  # Prod

  deploy-infra-prod:
    needs:
      - get-version
      - validate-staging-rust
    uses: ./.github/workflows/deploy-infra.yml
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      environment: "prod"
      environment_url: https://cast.walletconnect.com/health
      relay_url: "wss://relay.walletconnect.com"
      cast_url: "https://cast.walletconnect.com"

  validate-prod-rust:
    needs: [deploy-infra-prod]
    uses: ./.github/workflows/validate.yml
    secrets: inherit
    with:
      environment: "PROD"


  validate-swift-prod:       
    needs: [deploy-infra-prod]
    uses: ./.github/workflows/validate_swift.yml
    with:
      notify-endpoint: 'cast.walletconnect.com'
      relay-endpoint: 'relay.walletconnect.com' 
  