name: validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to validate"
        required: true
        default: "staging"
        type: choice
        options:
          - prod
          - staging
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        run: cargo test --test integration
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          TEST_ENV: ${{ inputs.environment }}
