name: validate

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the environment to validate"
        required: true
        default: "staging"
        type: choice
        options:
          - PROD 
          - STAGING
  workflow_call:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: "STAGING"
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: checkout
        uses: actions/checkout@v3    

      - name: Run integration tests
        run: cargo test --test integration
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          ENVIRONMENT: ${{ inputs.environment }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
